version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      MAVEN_OPTS: -Xmx1g
      TERM: dumb
      TZ: /usr/share/zoneinfo/America/Los_Angeles

    branches:
      ignore:
        - /rel\/.*/

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Build and Install Dependencies
          command: mvn clean install -DskipTests -pl manifold-deps-parent/manifold-json-test -am
      - run:
          name: Run Specific Test
          command: mvn -pl manifold-deps-parent/manifold-json-test test -Dtest=manifold.api.json.RequesterTest#httpPostRequestWithParameterizedUrlSuffixWithParams
      - run:
          name: Run tests without NonDex
          command: mvn test -B
      - run:
          name: Run tests with NonDex
          command: mvn -pl manifold-deps-parent/manifold-json-test edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=manifold.api.json.RequesterTest#httpPostRequestWithParameterizedUrlSuffixWithParams
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
            find . -type f -regex ".*/target/surefire-reports/.*-output.txt" -exec cp {} ~/junit/ \;
          when: always
      - deploy:
          name: Upload artifacts
          command: ./.circleci/deploy_snapshot.sh
      - store_artifacts:
          path: ~/junit
      - store_test_results:
          path: ~/junit
      - run:
          name: Trigger IDE tests
          command: curl -X POST https://circleci.com/api/v1.1/project/github/manifold-systems/manifold-ij?circle-token=${MANIFOLD_IJ_API_TOKEN}

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}